<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="add_fooditem.aspx.cs" Inherits="add_fooditem" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<br />
<br />
    <center>
<caption><h1>add food items</h1></caption>
<hr />
<table>


<tr>

<td>
<h5>MENU_NAME</h5>
</td>
<td>
    <asp:DropDownList ID="DropDownList1" AutoPostBack="true" runat="server" 
        onselectedindexchanged="DropDownList1_SelectedIndexChanged">
    </asp:DropDownList>
</td>
</tr>
<tr>
<td>
<h5>FOOD_NAME</h5>
</td>
<td>
    <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
    <%--<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBox2" Text="enter food name"></asp:RequiredFieldValidator>--%>
</td>
</tr>
<tr>
<td>
 <h5>FOOD_PRICE</h5>   
</td>
<td>
    <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
   <%-- <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" Text="enter the price" ControlToValidate="TextBox3"></asp:RequiredFieldValidator>--%>
</td>
</tr>
<tr>
<td>
<h5>FOOD_PIC</h5>
</td>
<td>
    <asp:FileUpload ID="FileUpload1" runat="server" />
</td>
</tr>
</table>
<br />
  <br />
<asp:Button ID="addfood" runat="server" Text="ADD FOOD" CssClass="button-27" 
            onclick="addfood_Click"/>
  <br />
  <br />
  <hr />
  <br />
    <asp:GridView ID="GridView1" runat="server"  CssClass="table text-start align-middle table-bordered  mb-0" DataKeyNames="food_id" 
            DataSourceID="s1" AutoGenerateColumns="False" AllowPaging="True" PageSize="5" 
            BorderStyle="None" BorderWidth="1px" BorderColor="#CCCCCC" RowStyle-Font-Bold="true"
    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" 
            BackColor="White" ForeColor="Black" GridLines="Horizontal">
    <Columns>
    <asp:BoundField DataField="food_id" HeaderText="food_id" />
    <asp:BoundField DataField="menu_name" HeaderText="menu_name" />
    <asp:BoundField DataField="food_name" HeaderText="food_name" />
    <asp:BoundField DataField="food_price" HeaderText="food_price" />
    <asp:ImageField DataImageUrlField="food_pic" HeaderText="food_pic" ControlStyle-Height="80" ControlStyle-Width="100">
<ControlStyle Height="80px" Width="100px"></ControlStyle>
    </asp:ImageField>
    </Columns>
        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
        <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F7F7F7" />
        <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
        <SortedDescendingCellStyle BackColor="#E5E5E5" />
        <SortedDescendingHeaderStyle BackColor="#242121" />
    </asp:GridView>
    <asp:SqlDataSource ID="s1" runat="server" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\food.mdf;Integrated Security=True;User Instance=True" 
    ProviderName="System.Data.SqlClient" SelectCommand="select * from food_items order by food_id" UpdateCommand="update food_items set food_name=@food_name,food_price=@food_price,food_pic=@food_pic where food_id=@food_id" 
    DeleteCommand="delete from food_items where food_id=@food_id">
    </asp:SqlDataSource>
    
    <asp:Label ID="Label1" runat="server" ></asp:Label>
</center>

</asp:Content>

