<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="add_menu.aspx.cs" Inherits="add_menu" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <center>
    <caption><h1>add food menu</h1></caption>
    <hr />
<table style="width: 321px; height: 88px">
<tr>
<td>
  <h5>  MENU</h5> 
</td>
<td>
 <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    <%--<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBox1" Text="enter menu name"></asp:RequiredFieldValidator>--%>
</td>
</tr>
</table>

    <asp:Button ID="addmenu" runat="server" Text="ADD MENU" CssClass="button-27"  onclick="addmenu_Click"/>
<br /><br />
<hr />
        <asp:GridView ID="GridView1" runat="server"  CssClass="table text-start align-middle table-bordered  mb-0" DataKeyNames="menu_id" 
            DataSourceID="s1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        BorderStyle="None" BorderWidth="1px" BorderColor="#CCCCCC" 
            RowStyle-Font-Bold="true" CellPadding="4" BackColor="White" ForeColor="Black" 
            GridLines="Horizontal">
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
        <asp:SqlDataSource ID="s1" runat="server" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\food.mdf;Integrated Security=True;User Instance=True"
        ProviderName="System.Data.SqlClient" SelectCommand="select * from menu" UpdateCommand="update menu set menu_name=@menu_name where menu_id=@menu_id" DeleteCommand="delete from menu where menu_id=@menu_id"> 
        </asp:SqlDataSource>
        <asp:Label ID="Label1" runat="server"></asp:Label>
</center>






</asp:Content>

