<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="admin_checkout.aspx.cs" Inherits="admin_checkout" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<br />
<br />
<center>
<h1>Order History</h1>
<hr />
<br />
<br />

        <asp:GridView ID="GridView1" CssClass="table text-start align-middle table-bordered  mb-0" runat="server" 
        DataSourceID="s1" AutoGenerateDeleteButton="True"  
        BorderStyle="None" BorderWidth="1px" BorderColor="#CCCCCC" 
        RowStyle-Font-Bold="true" CellPadding="4" AutoGenerateColumns="False" 
        BackColor="White" ForeColor="Black" GridLines="Horizontal" 
        >
            <Columns>
                <asp:BoundField DataField="username" HeaderText="username" 
                    SortExpression="username" />
                <asp:BoundField DataField="address" HeaderText="address" 
                    SortExpression="address" />
                <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                <asp:BoundField DataField="mobile_no" HeaderText="mobile_no" 
                    SortExpression="mobile_no" />
                <asp:BoundField DataField="pay_method" HeaderText="pay_method" 
                    SortExpression="pay_method" />
                <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>



        <asp:SqlDataSource ID="s1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:foodConnectionString %>" 
        SelectCommand="SELECT [username], [address], [city], [email], [mobile_no], [pay_method], [date] FROM [checkout]"> 
        </asp:SqlDataSource>
        <asp:Label ID="Label1" runat="server"></asp:Label>

        <br /><br /><br />
</center>
</asp:Content>

