<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="admin_viewcart.aspx.cs" Inherits="admin_viewcart" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<br />
<br />
<center>
<h1>Show Cart</h1>
<hr />
<br />
<br />
        <asp:GridView ID="GridView1" runat="server" CssClass="table text-start align-middle table-bordered  mb-0" DataKeyNames="cart_id" 
        DataSourceID="s1" AutoGenerateDeleteButton="True"  
        BorderStyle="None" BorderWidth="1px" BorderColor="#CCCCCC" 
        RowStyle-Font-Bold="true" CellPadding="4" BackColor="White" ForeColor="Black" 
        GridLines="Horizontal">
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
        <asp:SqlDataSource ID="s1" runat="server" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\food.mdf;Integrated Security=True;User Instance=True"
        ProviderName="System.Data.SqlClient" SelectCommand="select * from place_order order by cart_id" DeleteCommand="delete from place_order where cart_id=@cart_id"> 
        </asp:SqlDataSource>
        <asp:Label ID="Label1" runat="server"></asp:Label>
</center>
</asp:Content>

